CREATE DATABASE MYCLASS;


USE MYCLASS;


CREATE TABLE USUARIO(
	ID INTEGER AUTO_INCREMENT UNIQUE,
	CODIGO VARCHAR(255),
	CORREO VARCHAR(255) NOT NULL UNIQUE,
	AVATAR VARCHAR(255) NOT NULL UNIQUE DEFAULT 'www.myclass.es/img/avatardefault.jpg',
	NOMBRE_FULL	VARCHAR(255) NOT NULL,
	FAMILIA_PROF VARCHAR(255) NOT NULL,
	FECHA_REG DATE NOT NULL,
	EDAD INTEGER NOT NULL,
	DNI VARCHAR(255),
	ADMIN_VALUE TINYINT(1) NOT NULL DEFAULT '0',
	
	
	PRIMARY KEY(CODIGO)
);


CREATE TABLE GRUPO(
	ID INTEGER AUTO_INCREMENT UNIQUE,
	CODIGO VARCHAR(255),
	NOMBRE VARCHAR(255) NOT NULL,
	CAPACIDAD INTEGER NOT NULL DEFAULT '30', 
	COD_OWNER VARCHAR(255) NOT NULL,
	
	PRIMARY KEY (CODIGO),
	
	
	CONSTRAINT OWNER_FK FOREIGN KEY (COD_OWNER) REFERENCES USUARIO(CODIGO)
		
);


CREATE TABLE USERGROUP(
	COD_USER VARCHAR(255) NOT NULL,
	COD_GROUP VARCHAR(255) NOT NULL,
	
	
	CONSTRAINT USER_FK FOREIGN KEY (COD_USER) REFERENCES USUARIO(CODIGO),
	CONSTRAINT GROUP_FK FOREIGN KEY (COD_GROUP) REFERENCES GRUPO(CODIGO)
);
