CREATE DATABASE MYCLASS;


USE MYCLASS;


-- NOTICIAS, RECOGE EL LINK DEL AGREGADOR RSS DE CADA PAGINA Y LO ENLACA A CADA FAMILIA PROFESIONAL
CREATE TABLE NOTICIAS(
	AGREGADOR VARCHAR(255) NOT NULL,
	FAMILIA_PROF VARCHAR(255) NOT NULL
);

-- USUARIOS, RELACION CON FAMILIA PROFESIONAL
CREATE TABLE USUARIO(
	ID INTEGER AUTO_INCREMENT UNIQUE,
	CODIGO VARCHAR(255),
	CORREO VARCHAR(255) NOT NULL UNIQUE,
	AVATAR VARCHAR(255) NOT NULL UNIQUE DEFAULT 'www.myclass.es/img/avatardefault.jpg',
	NOMBRE_FULL	VARCHAR(255) NOT NULL,
	FAMILIA_PROF VARCHAR(255) NOT NULL,
	FECHA_REG DATE NOT NULL,
	EDAD INTEGER NOT NULL,
	DNI VARCHAR(255),
	ADMIN_VALUE TINYINT(1) NOT NULL DEFAULT '0',
	
	
	PRIMARY KEY(CODIGO),
	
	CONSTRAINT FPROF_FK FOREIGN KEY FAMILIA_PROF REFERENCES NOTICIAS(FAMILIA_PROF)
);


-- GRUPO, RELACION COD_OWNER CON CODIGO DE USUARIO
CREATE TABLE GRUPO(
	ID INTEGER AUTO_INCREMENT UNIQUE,
	CODIGO VARCHAR(255),
	NOMBRE VARCHAR(255) NOT NULL,
	CAPACIDAD INTEGER NOT NULL DEFAULT '30', 
	COD_OWNER VARCHAR(255) NOT NULL,
	
	PRIMARY KEY (CODIGO),
	
	
	CONSTRAINT OWNER_FK FOREIGN KEY (COD_OWNER) REFERENCES USUARIO(CODIGO)
		
);


-- RELACION ENTRE USUARIO - GRUPO, FOREIGN KEYS CON TABLA GRUPO Y TABLA USUARIO
CREATE TABLE USERGROUP(
	COD_USER VARCHAR(255) NOT NULL,
	COD_GROUP VARCHAR(255) NOT NULL,
	
	
	CONSTRAINT USER_FK FOREIGN KEY (COD_USER) REFERENCES USUARIO(CODIGO),
	CONSTRAINT GROUP_FK FOREIGN KEY (COD_GROUP) REFERENCES GRUPO(CODIGO)
);




-- CREACION DE TAREA QUE ENLAZA CADA UNA DE ESTAS A UN GRUPO
CREATE TABLE TAREAS(
	CODIGO VARCHAR(255),
	COD_GRUPO VARCHAR(255) NOT NULL,
	TITLE_TAREA VARCHAR(255) NOT NULL,
	BODY_TAREA VARCHAR(255) NOT NULL,
	FECHA_ENTREGA DATE NOT NULL,
	
	
	PRIMARY KEY (CODIGO)
	
);


-- NOTAS DE CADA USUARIOS ENLAZADAS A UNA TAREA Y A UN USUARIO CON LAS FKs
CREATE TABLE USERNOTAS(
	COD_USER VARCHAR(255) NOT NULL,
	COD_TAREA VARCHAR(255) NOT NULL,
	NOTA FLOAT NOT NULL,
	
	
	CONSTRAINT USER_FK FOREIGN KEY (COD_USER) REFERENCES USUARIO(CODIGO),
	CONSTRAINT WORK_FK FOREIGN KEY (COD_TAREA) REFERENCES TAREAS(CODIGO)
);

